version: "3.9"
services:
  db:
    image: mongo
    container_name: dbmongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: practica1-so
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - D:/Documentos/go/src/github.com/MarcosC19/SO1-Practica1-201900874/backend/volumenBack:/data/db
    networks:
      - practica1

  backend:
    image: curtex19/backend_p1_201900874
    container_name: backend_p1_201900874
    environment:
      - HOSTIP=192.168.1.11
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db
    networks:
      - practica1

  frontend:
    image: curtex19/frontend_p1_201900874
    container_name: frontend_p1_201900874
    environment:
      - REACT_APP_HOSTIP=192.168.1.11
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
    networks:
      - practica1

volumes:
  mongodata:

networks:
  practica1:
    name: "practica1"
    driver: bridge
